[[plugins]]
repo = 'Shougo/dein.vim'




# map <Leader>h <Plug>(easymotion-linebackward)
# map <Leader>l <Plug>(easymotion-lineforward)
#
# map <Leader>j <Plug>(easymotion-j)
# map <Leader>k <Plug>(easymotion-k)






# if dein#util#_is_windows()
#     source ~/appdata/local/nvim/plugins/toggleterm.lua
#   else
#     source ~/.config/nvim/plugins/toggleterm.lua
#   endif
# [[plugins]]
# repo = 'uga-rosa/translate.nvim'



