# vim-code-dark (VS Code風カラーテーマ)
[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_add = '''
    colorscheme codedark
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

# 括弧の操作
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0
hook_add = '''
if has('mac')
  source ~/.config/nvim/plugins/coc-setting.lua
elseif has('unix')
  source ~/AppData/Local/nvim/plugins/coc-setting.lua
elseif has('win32')
  source ~/AppData/Local/nvim/plugins/coc-setting.lua
end
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  map <leader>f <Plug>(easymotion-bd-f)
  nmap <leader>f <Plug>(easymotion-overwin-f)
  let g:EasyMotion_smartcase = 1
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    vnoremap <leader>c :TComment<CR>
'''

# gitgutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    set signcolumn=yes
    let g:gitgutter_async = 1
    let g:gitgutter_sign_modified = '%'
    let g:gitgutter_map_keys = 0
    nmap ]c <plug>(gitgutternexthunk)
    nmap [c <plug>(GitGutterPrevHunk)
    highlight GitGutterAdd ctermfg=green
    highlight GitGutterChange ctermfg=yellow
    highlight GitGutterDelete ctermfg=red
    highlight GitGutterChangeDelete ctermfg=yellow
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
    let g:fern#default_hidden=1
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
  nmap <leader>qq <cmd>Gina status<cr>
'''



[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup end
'''
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_cmd = ['Telescope']
hook_add = '''
    nnoremap <leader>hf <cmd>Telescope find_files<cr>
    nnoremap <leader>hg <cmd>Telescope live_grep<cr>
    nnoremap <leader>hb <cmd>Telescope buffers<cr>
    nnoremap <leader>; <cmd>Telescope resume<cr>
'''

[[plugins]]
repo = 'github/copilot.vim'
hook_add = '''
if has('win32')
  let g:copilot_proxy = "172.21.252.1:12080"
end
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'

[[plugins]]
repo = 'akinsho/toggleterm.nvim'
hook_add = """
if has('mac')
  source ~/.config/nvim/plugins/toggleterm.lua
elseif has('unix')
  source ~/AppData/Local/nvim/plugins/toggleterm.lua
elseif has('win32')
  source ~/AppData/Local/nvim/plugins/toggleterm.lua
end
"""

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
